#!/bin/bash

if ! command -v column &>/dev/null; then
	echo "Installing column dependency"
	sudo apt install bsdutils -y
fi

# sudo nmap -O  192.168.1.201 | grep -w "Running:" | cut -d ":" -f 2- | awk "{$1=$1};1"

routes=$(ip -o -f inet route show dev eth0 | sed -n \$p | awk '{print $1}')
defaultgw=$(sudo ip route | grep "default via" -w | awk '{print $3}')
selfmac=$(ip -o link show eth0 | cut -d " " -f 20)
selfip=$(ip addr show dev eth0 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
count=0
options="$(
	sudo nmap -sn -oG - $routes |
		while read -r line || [[ "$line" ]]; do

			[[ "$line" =~ ^[[:space:]]*# ]] && continue

			count=$((count + 1))
			ipaddress="$(echo $line | awk '{print $2}')"
			result="$(sudo nmap -sn $ipaddress | grep "MAC Address:")"
			hostname=$(nslookup $ipaddress | grep "name = " | awk '{print $4}' | sed 's/\.$//')

			if [ "$hostname" = "" ]; then
				hostname="-"
			fi
			echo "$ipaddress $hostname"
		done
)"

dialog --keep-tite --menu "Select options:" 22 76 16 $options
