#!/bin/bash

if ! command -v column &>/dev/null; then
	echo "Installing column dependency"
	sudo apt install bsdutils -y
fi

function main() {

	device="$1"

	if [ "$device" = "" ]; then
		device="eth0"
	fi

	echo "Scanning network $device, please wait..."
	routes=$(ip -o -f inet route show dev $device | sed -n \$p | awk '{print $1}')

	declare -a array

	i=1
	j=1

	sudo nmap -sn -oG - $routes >/tmp/nettool.tmp

	while read -r line; do
		[[ "$line" =~ ^[[:space:]]*# ]] && continue
		ipaddress="$(echo $line | awk '{print $2}')"
		hostname=$(nslookup $ipaddress | grep "name = " | awk '{print $4}' | sed 's/\.$//')

		if [ "$hostname" = "" ]; then
			hostname="-"
		fi

		array[$i]=$j
		((j++))
		array[($i + 1)]="$ipaddress $hostname"
		((i = ($i + 2)))
	done </tmp/nettool.tmp

	rm /tmp/nettool.tmp

	TERMINAL=$(tty)
	HEIGHT=20
	WIDTH=76
	CHOICE_HEIGHT=16
	BACKTITLE="Network Browser"
	TITLE="Choose Host"
	MENU="Select:"

	CHOICE=$(dialog --backtitle "$BACKTITLE" \
		--title "$TITLE" \
		--menu "$MENU" \
		$HEIGHT $WIDTH $CHOICE_HEIGHT \
		"${array[@]}" \
		2>&1 >$TERMINAL)

	echo $CHOICE
}

main "$1"
